M48
; DRILL file {KiCad 9.0.4} date 2025-10-24T17:45:05+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-24T17:45:05+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X49.101Y-127.354
X57.101Y-127.354
T2
X68.275Y-114.427
X111.608Y-122.199
M30
