M48
; DRILL file {KiCad 9.0.4} date 2025-10-24T17:48:04+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-24T17:48:04+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X86.639Y-99.797
X154.635Y-81.509
T2
X87.884Y-119.71
X148.59Y-93.243
M30
